name: loni_admin
description: "Admin application for LONI Africa platform."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get_it: ^9.2.0
  go_router: ^17.0.0
  hugeicons: ^1.1.2
  url_launcher: ^6.3.2
  retrofit: ^4.9.1
  logger: ^2.6.2
  provider: ^6.1.5+1
  package_info_plus: ^9.0.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  share_plus: ^12.0.1
  flutter_svg: ^2.2.3
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_core: ^4.2.1
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_native_splash: ^2.4.7
  flutter_hooks: ^0.21.3+1
  timeago: ^3.7.1
  data_table_2: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  json_serializable: ^6.11.3
  build_runner: ^2.10.4
  retrofit_generator: ^10.2.0

dependency_overrides:
  analyzer: 8.4.0

flutter:
  generate: true
  uses-material-design: true
